-- set
-- search_path = box;
--
-- truncate  table customer cascade;
--
--
-- alter table customer
--     add column encrytedPassword text ;
-- alter table customer
--     add column enabled boolean default false ;